export const mockCategories = [
  { id: "shelter",    name_ja: "シェルター",    icon: "Tent",           sort_order: 1  },
  { id: "sleeping",   name_ja: "シュラフ・寝具", icon: "BedDouble",      sort_order: 2  },
  { id: "clothing",   name_ja: "衣類",          icon: "Shirt",          sort_order: 3  },
  { id: "footwear",   name_ja: "靴・足回り",    icon: "Footprints",     sort_order: 4  },
  { id: "backpack",   name_ja: "バックパック",  icon: "Backpack",       sort_order: 5  },
  { id: "navigation", name_ja: "ナビゲーション", icon: "Compass",       sort_order: 6  },
  { id: "safety",     name_ja: "安全装備",      icon: "ShieldCheck",    sort_order: 7  },
  { id: "cooking",    name_ja: "調理器具",      icon: "Flame",          sort_order: 8  },
  { id: "food",       name_ja: "食料・行動食",  icon: "Apple",          sort_order: 9  },
  { id: "tools",      name_ja: "道具・その他",  icon: "Wrench",         sort_order: 10 },
];

export const mockGearItems = [
  {
    id: "1",
    name: "モンベル レインダンサー ジャケット",
    category_id: "clothing",
    weight_g: 285,
    is_essential: true,
    notes: "ゴアテックス素材 / Mサイズ",
    image_url: "https://picsum.photos/seed/rainjacket/400/400",
    brand: "mont-bell",
  },
  {
    id: "2",
    name: "モンベル アルパインクルーザー 2500",
    category_id: "footwear",
    weight_g: 620,
    is_essential: true,
    notes: "3シーズン対応 / 27.0cm",
    image_url: "https://picsum.photos/seed/hikingboots/400/400",
    brand: "mont-bell",
  },
  {
    id: "3",
    name: "PETZL ACTIK CORE",
    category_id: "safety",
    weight_g: 87,
    is_essential: true,
    notes: "350ルーメン / 充電式",
    image_url: "https://picsum.photos/seed/headlamp/400/400",
    brand: "PETZL",
  },
  {
    id: "4",
    name: "モンベル UL ドームシェルター 2型",
    category_id: "shelter",
    weight_g: 1340,
    is_essential: false,
    notes: "2人用 / フライ込み",
    image_url: "https://picsum.photos/seed/tent/400/400",
    brand: "mont-bell",
  },
  {
    id: "5",
    name: "イスカ エア 630",
    category_id: "sleeping",
    weight_g: 780,
    is_essential: false,
    notes: "快適温度 -7℃ / ダウン",
    image_url: "https://picsum.photos/seed/sleepingbag/400/400",
    brand: "ISUKA",
  },
  {
    id: "6",
    name: "OSPREY ケストレル 48",
    category_id: "backpack",
    weight_g: 1420,
    is_essential: false,
    notes: "48L / レインカバー付き",
    image_url: "https://picsum.photos/seed/backpack48/400/400",
    brand: "OSPREY",
  },
  {
    id: "7",
    name: "ガーミン inReach Mini 2",
    category_id: "navigation",
    weight_g: 100,
    is_essential: false,
    notes: "衛星通信・GPS対応",
    image_url: "https://picsum.photos/seed/garmin/400/400",
    brand: "Garmin",
  },
  {
    id: "8",
    name: "プリムス P-153 ウルトラバーナー",
    category_id: "cooking",
    weight_g: 66,
    is_essential: false,
    notes: "火力4200kcal/h",
    image_url: "https://picsum.photos/seed/burner/400/400",
    brand: "PRIMUS",
  },
  {
    id: "9",
    name: "チタンコッヘル 0.9L",
    category_id: "cooking",
    weight_g: 120,
    is_essential: false,
    notes: "チタン製 / 軽量",
    image_url: "https://picsum.photos/seed/titanpot/400/400",
    brand: "EVERNEW",
  },
  {
    id: "10",
    name: "行動食セット（1日分）",
    category_id: "food",
    weight_g: 500,
    is_essential: true,
    notes: "ナッツ・チョコ・ジェル",
    image_url: "https://picsum.photos/seed/trailfood/400/400",
    brand: "",
  },
  {
    id: "11",
    name: "SOL エマージェンシーブランケット",
    category_id: "safety",
    weight_g: 50,
    is_essential: true,
    notes: "アルミ蒸着 / 緊急用",
    image_url: "https://picsum.photos/seed/emergencyblanket/400/400",
    brand: "SOL",
  },
  {
    id: "12",
    name: "LEKI トレッキングポール（2本）",
    category_id: "tools",
    weight_g: 440,
    is_essential: false,
    notes: "カーボン製 / 折りたたみ式",
    image_url: "https://picsum.photos/seed/trekpole/400/400",
    brand: "LEKI",
  },
];

export const mockPackages = [
  {
    id: "pkg-1",
    name: "北アルプス縦走セット",
    description: "槍・穂高などの本格縦走向け。2泊3日想定。安全装備完備。",
    mountain_type: "高山・縦走",
    total_weight_g: 4808,
    is_public: true,
    item_count: 10,
  },
  {
    id: "pkg-2",
    name: "低山日帰りセット",
    description: "高尾山・丹沢などの日帰りハイキング向け。軽量重視。",
    mountain_type: "低山・ハイキング",
    total_weight_g: 1442,
    is_public: false,
    item_count: 5,
  },
  {
    id: "pkg-3",
    name: "富士山セット（夏）",
    description: "7〜9月の富士登山向け。山小屋泊想定。",
    mountain_type: "富士山",
    total_weight_g: 2185,
    is_public: true,
    item_count: 7,
  },
];

export const mockAiResult = {
  mountain: "槍ヶ岳",
  month: 8,
  nights: 2,
  recommended_items: [
    { name: "モンベル レインダンサー ジャケット", category: "衣類",          reason: "北アルプスは午後に雷雨が多い。必携。",          from_user_gear: true },
    { name: "モンベル アルパインクルーザー 2500", category: "靴・足回り",    reason: "槍ヶ岳の岩稜帯はソールの硬い登山靴が必要。",    from_user_gear: true },
    { name: "PETZL ACTIK CORE",                  category: "安全装備",      reason: "早朝出発のため必須。予備電池も確認を。",         from_user_gear: true },
    { name: "イスカ エア 630",                   category: "シュラフ",      reason: "8月でも夜は10℃以下になる。このシュラフで安心。", from_user_gear: true },
    { name: "SOL エマージェンシーブランケット",   category: "安全装備",      reason: "緊急時のビバーク対応。必ず携行。",              from_user_gear: true },
  ],
  missing_items: [
    { name: "ヘルメット（登山用）",  priority: "必須",       reason: "槍ヶ岳山頂付近は落石リスクがある。レンタル可能だが持参推奨。" },
    { name: "防寒着（フリース等）",  priority: "必須",       reason: "標高3180m。8月でも早朝は5℃以下になることがある。" },
    { name: "日焼け止めSPF50以上",   priority: "推奨",       reason: "高山は紫外線が平地の約1.5倍。" },
    { name: "高山病対策薬",          priority: "あると便利", reason: "初めて3000m超に登る場合は医師に相談を。" },
  ],
  warnings: [
    "8月の槍ヶ岳は登山者が非常に多く、山小屋は早めの予約が必要です。",
    "稜線上は午後に雷雲が発生しやすいため、13時までには稜線を外れる計画を。",
  ],
  total_weight_estimate_g: 3780,
  reasoning: "2泊3日の槍ヶ岳登山では安全装備と防寒対策が最優先です。あなたの装備は基本的に揃っていますが、ヘルメットと防寒着の追加を強く推奨します。総重量は約3.8kgと適正範囲内です。",
};
